### ISSUE TITLE
No module named MySQLdb  请问这个应该怎么解决啊 T T

### ISSUE THREAD

**Issue by zhalice2011** [x-spiders/baiduyun-spider#1]
$ python bin/spider.py --seed-user
Traceback (most recent call last):
  File "bin/spider.py", line 3, in <module>
    import MySQLdb as mdb
ImportError: No module named MySQLdb

**Comment by 131250208** [comment]
pip install mysql-python

**Comment by chen-jinchuan** [comment]
也可以使用pymysql 模块替换mysqldb
